# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/tasit-sdk

    steps:
      - checkout

      - run:
          name: install npm
          command: "sudo npm install -g npm@latest"

      - run:
          name: install greenkeeper-lockfile
          command: "sudo npm install -g greenkeeper-lockfile@latest"

      - run:
          name: run greenkeeper-lockfile-update
          command: "greenkeeper-lockfile-update"

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-

      - run:
          name: install npm packages
          command: npm run bootstrap

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: run test suite
          command: npm test

      - run:
          name: run greenkeeper-lockfile-upload
          command: "greenkeeper-lockfile-upload"
